### PR TITLE
Added 100+ emoji dividers

### PR DESCRIPTION
**Pull request by amrutha3**
I've added more emoji dividers

### CODE REVIEW

**Comment by RDIL** [comment]
oh my
I’m going to take some time to realize what just happened lol

**Comment by RDIL** [comment]
I know this is a lot to ask, but is their a chance you could also update the docs (projectroot/docs/index.rst)?  (If no I can do it myself)

**Comment by amrutha3** [comment]
I've updated the documents

**Comment by RDIL** [comment]
@CoffeeGoddess can you merge after deploy?

**Pull request merged**
