### PR TITLE
Added A dice rolling sim

### PR DESCRIPTION
**Pull request by BallisticZer0**
I also made a few note on how i made the thing and some other helpful notes on the random function and time function

### CODE REVIEW

**Comment by RDIL** [comment]
Hmm, this could be a fun easter egg in the package.  I'll merge, but won't include docs for the sake of it ;)

**Comment by RDIL** [comment]
just waiting for travis

**Comment by BallisticZer0** [comment]
Ok thanks i made this in 3.7 so somethings are just not liking it.

**Comment by BallisticZer0** [comment]
Ok thank you. hope this is what you needed.

**Pull request merged**
