### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dowlandaiello**
- [x] Removed unnecessary str() casts on already declared strings (i.e. custom_div = str(""))

### CODE REVIEW

**Comment by RDIL** [comment]
haha need to do that again sorry <3

**Comment by RDIL** [comment]
Now my pals the CIs do their part

**Comment by dowlandaiello** [comment]
Lol why do you need 10 different checks for a list of string definitions?

**Comment by RDIL** [comment]
don't bully me it was meh ocd's fault

**Pull request merged**
