### PR TITLE
done

### PR DESCRIPTION
**Pull request by xoreo**
## Description  
I made this entire repo in just a few lines. Maybe you can learn a thing or two from it.

## Context  
This might be a good idea to merge.

## Additional Information  
I deleted all of the Pypi stuff, so you can put that back. But the core of the repo is now much more simple and easier to contribute to.

### CODE REVIEW

**Comment by RDIL** [comment]
No, you can't.

**Comment by RDIL** [comment]
Just for now.

**Comment by dowlandaiello** [comment]
Actually, you can resolve a ```random.randint``` statement from a string (```eval```). @RDIL

**Comment by RDIL** [comment]
Let’s hold off on merging this until we can merge it onto the rewrite
branch.

**Comment by RDIL** [comment]
Oh well

**Pull request merged**
