### PR TITLE
Merge tests to a single task

### PR DESCRIPTION
**Pull request by RDIL**
## Description

  
Merges NodeJS and Python tests into 1 task

### CODE REVIEW

**Comment by RDIL** [comment]
Hey @fkorotkov how can we use both `python:latest` and `nodejs:latest` in the same task?

**Comment by fkorotkov** [comment]
@RDIL you'll need to build your own container. This issue will help with such problems in future: https://github.com/cirruslabs/cirrus-ci-docs/issues/85

**Comment by RDIL** [comment]
Thanks

**Comment by RDIL** [comment]
@fkorotkov in the meantime do you think I should install Linuxbrew to install nodejs?

**Comment by fkorotkov** [comment]
Why do you want to merge Node and Python? Do they depend on each other?

**Comment by RDIL** [comment]
Yes, my tests need both present and Travis allowed me to use `nvm install 11` while having `language: python`.

**Comment by RDIL** [comment]
@fkorotkov I just found a solution: I moved on to macOS so now I can `brew install python@3` and `brew install node`!

**Pull request merged**
